language: go
sudo: required
services:
- docker
go:
- '1.11'
script:
- echo "bitcoin Prometheus Exporter - commit:${TRAVIS_COMMIT}"
- make test
- make container VERSION=$TRAVIS_BRANCH
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then docker login -u $DOCKER_USERNAME
  -p $DOCKER_PASSWORD ; make push VERSION=$TRAVIS_BRANCH ; fi
