[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"
